apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 30080
      targetPort: 8080
  selector:
    app: app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: database
